build.gradle.kts

* Release 1.1.0
* Release 1.1.0
* Release 1.1.0

Release 1.1.0

---

gradle/wrapper/gradle-wrapper.properties

gradle is version up.
gradle wrapper version up.
Users are not affected.

gradle version up

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/commit_lint.yaml
commitlint.config.js
package.json

* To apply the same commit policy to many contributers.
* Add commit lint CI configuration 
* Add commit lint rule file
| Commit type | Description               |
|-------------|---------------------------|
| feat        | New Feature               |
| fix         | Fix bug                   |
| docs        | Documenation only changed |
| ci          |Change CI configuration|
| refactor    |Not a bug fix or add feature, just refactoring code|
| test        |Add Test case or fix wrong test case|
| style       |Only change the …

Apply Commit lint on Pull Request

---

build.gradle.kts

version up
version up
version up

chore: jdsl version up 2.0.4.RELEASE

---

examples/spring-boot-3/build.gradle.kts

* The dependency remarked in the spring-boot-3 example is actually an incompatible dependency with springboot 3.
-- korean
* spring-boot-3 example 에 주석으로 명시된 dependency가 실제로 springboot 3과 호환되지 않는 의존성입니다.
* Changed remark to `spring-data-kotlin-jdsl-starter-jakarta` compatible with springboot 3.
-- korean
* springboot 3과 호환되는 `spring-data-kotlin-jdsl-starter-jakarta`로 주석을 변경하였습니다. …

fix remarks in spring-boot-3 example

---

render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNullIfSerializer.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNullIfSerializerTest.kt

- Implement `JpqlNullIfSerializer`
| refactor    | Not a bug fix or add feature, just …

Add jpql nullif serializer

---

query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/from/impl/JpqlJoinedEntity.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlBetweenSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlCountSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlDerivedEntitySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlEntityPropertySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlEntitySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlEqualSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlExpressionSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlGreaterThanOrEqualToSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlGreaterThanSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInSubquerySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInnerAssociationJoinSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInnerJoinSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlIsNullSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlJoinedEntitySerializerTest.kt
render/sql/src/test/kotlin/com/linecorp/kotlinjdsl/render/sql/serializer/impl/ColumnSerializerTest.kt

There are some missing test for jpql serializers
- add some test

Add missing tests for jpql serializers

---

render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNullSerializer.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNullSerializerTest.kt

* Explain why you're making this change and what problem you're trying to solve.
- Implement `JpqlNullSerializer`
- Implement Unit test for `JpqlNullSerializer` …

Add jpql null serializer

---

render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlCaseValueSerializer.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlCaseValueSerializerTest.kt

* Implements `JpqlCaseValueSerializer`
| refactor    | Not a bug fix or add feature, …

Add jpql case value serializer

---

render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlPlusSerializer.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlMinusSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlPlusSerializerTest.kt

* Explain why you're making this change and what problem you're trying to solve.
- Implement `JpqlPlusSerializer`
- Implement Unit test for `JpqlPlusSerializer`
- Implement Unit test for `JpqlMinusSerializer`
| docs        | …

Add jpql plus serializer and Unit test for jpql minus serializer

---

render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlFunctionSerializer.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlFunctionSerializerTest.kt

[#340 ](https://github.com/line/kotlin-jdsl/issues/340)
- Implement JpqlFunctionSerializer
- Implement Unit test for JpqlFunctionSerializer
| ci          | …

feat: implement JpqlFunctionSerializer

---

render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlIsNotNullSerializer.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlIsNotNullSerializerTest.kt

Add JpqlIsNotNullSerializer
Add tests
* List the modifications you've made in detail.
| …

feat(render): add serializer for jpql isNotNull

---

render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlUpdateQuerySerializer.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlDerivedEntitySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlEntityPropertySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlEntitySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInSubquerySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInnerAssociationJoinSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInnerJoinSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLeftJoinSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNewSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlOrSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlParamSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlPathPropertySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSelectQuerySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSortSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSubquerySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlTimesSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlUpdateQuerySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlValueSerializerTest.kt

- add missing serializer test
| refactor    | Not a bug fix or add feature, just …

Add serializer tests

---

render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlIsEmptySerializer.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlIsNotEmptySerializer.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlIsEmptySerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlIsNotEmptySerializerTest.kt

* Implements `JpqlIsEmptySerializer` & `JpqlIsNotEmptySerializer`
| refactor    | Not a …

feat: add JpqlIsEmptySerializer & JpqlIsNotEmptySerializer

---

render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotEqualSerializer.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotEqualSerializerTest.kt

Add JpqlNotEqualSerializer
Add tests
* List the modifications you've made in detail.
| …

feat(render): add serializer for jpql not equal

---

render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLessThanOrEqualToSerializer.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLessThanSerializer.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLessThanOrEqualToSerializerTest.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLessThanSerializerTest.kt

* `Implements JpqlLessThanOrEqualToSerializer & JpqlLessThanSerializer`
| refactor    | …

Implements JpqlLessThanOrEqualToSerializer & JpqlLessThanSerializer

---

example/eclipselink-javax/build.gradle.kts
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/annotation/CompositeId.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/author/Author.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/book/Book.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/book/BookAuthor.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/book/BookPrice.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/book/BookPublisher.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/book/Isbn.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/department/Department.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/employee/Employee.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/employee/EmployeeAddress.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/employee/EmployeeDepartment.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/employee/EmployeeSalary.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/employee/FullTimeEmployee.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/employee/PartTimeEmployee.kt
example/eclipselink-javax/src/main/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/entity/publisher/Publisher.kt
example/eclipselink-javax/src/main/resources/META-INF/persistence.xml
example/eclipselink-javax/src/test/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/delete/DeleteExample.kt
example/eclipselink-javax/src/test/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/select/SelectExample.kt
example/eclipselink-javax/src/test/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/update/UpdateExample.kt
example/eclipselink-javax/src/testFixtures/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/EntityManagerFactoryTestUtils.kt
example/eclipselink-javax/src/testFixtures/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/jpql/JpqlRenderContextUtils.kt
example/eclipselink-javax/src/testFixtures/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/reader/MultipleLinesSqlCommandFileReader.kt

- example for eclipselink-javax support module for users using elipselink without any spring dependency
- example and integration test for eclipselink-support-javax module
| docs        | Documentation only changed …

feat: implement ecliselink-javax support module example

---

example/eclipselink-javax/src/test/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/javax/select/SelectExample.kt
example/eclipselink/src/test/kotlin/com/linecorp/kotlinjdsl/example/eclipselink/select/SelectExample.kt
example/hibernate-javax/src/test/kotlin/com/linecorp/kotlinjdsl/example/jpql/hibernate/javax/select/SelectExample.kt
example/hibernate-reactive-javax/src/test/kotlin/com/linecorp/kotlinjdsl/example/hibernate/reactive/javax/jpql/select/SelectMutinySessionExample.kt
example/hibernate-reactive-javax/src/test/kotlin/com/linecorp/kotlinjdsl/example/hibernate/reactive/javax/jpql/select/SelectMutinyStatelessSessionExample.kt
example/hibernate-reactive-javax/src/test/kotlin/com/linecorp/kotlinjdsl/example/hibernate/reactive/javax/jpql/select/SelectStageSessionExample.kt
example/hibernate-reactive-javax/src/test/kotlin/com/linecorp/kotlinjdsl/example/hibernate/reactive/javax/jpql/select/SelectStageStatelessSessionExample.kt
example/hibernate-reactive/src/test/kotlin/com/linecorp/kotlinjdsl/example/hibernate/reactive/jakarta/jpql/select/SelectMutinySessionExample.kt
example/hibernate-reactive/src/test/kotlin/com/linecorp/kotlinjdsl/example/hibernate/reactive/jakarta/jpql/select/SelectMutinyStatelessSessionExample.kt
example/hibernate-reactive/src/test/kotlin/com/linecorp/kotlinjdsl/example/hibernate/reactive/jakarta/jpql/select/SelectStageSessionExample.kt
example/hibernate-reactive/src/test/kotlin/com/linecorp/kotlinjdsl/example/hibernate/reactive/jakarta/jpql/select/SelectStageStatelessSessionExample.kt
example/hibernate/src/test/kotlin/com/linecorp/kotlinjdsl/example/jpql/hibernate/select/SelectExample.kt
example/spring-data-jpa-javax/src/test/kotlin/com/linecorp/kotlinjdsl/example/spring/data/jpa/javax/jpql/select/SelectExample.kt
example/spring-data-jpa/src/test/kotlin/com/linecorp/kotlinjdsl/example/spring/data/jpa/jpql/select/SelectExample.kt

I found a wrong test case in SelectExample (most recently published book)
Fix wrong test case in SelectExample(the most recently published book) …

Fix wrong test case in SelectExample(the most recently published book)

---

dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/LocateDslTest.kt
query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlLocate.kt
query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLocateSerializer.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLocateSerializerTest.kt

- Support for String functions(locate)
- Add JpqlLocate, JpqlLocateSerializer, dsl for locate function with test …

Add String functions(locate)

---

dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/LengthDslTest.kt
query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlLength.kt
query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLengthSerializer.kt
render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLengthSerializerTest.kt

- Support for String functions(length)
- Add JpqlLength, JpqlLengthSerializer, dsl for length function with test …

Add String functions(length)
