- .gitignore
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/LocalPropertiesPlugin.kt
- buildSrc/src/main/kotlin/Plugins.kt
- buildSrc/src/main/kotlin/PublishPlugin.kt
- core/build.gradle.kts
- hibernate/build.gradle.kts
- spring/batch-infrastructure/build.gradle.kts
- spring/data-autoconfigure/build.gradle.kts
- spring/data-core/build.gradle.kts
- spring/data-starter/build.gradle.kts
Motivation:
Make publishing settings.
Refer to #8 
-- korean
maven 저장소에 배포될 수 있도록 sonatype 저장소에 배포하는 스크립트 작성
-- english
Create scripts to deploy to sonatype so that it can be published to maven.
Result:
-- korean
local.properties에 계정 정보를 적는 것으로 sonatype에 배포할 수 있게 됩니다.
-- english
By writing down account in local.properties, you can publish it to sonatype. 
```properties
signing.keyId={your signing.keyId}
signing.password={your signing.password}
signing.secretKeyRingFile={your signing.secretKeyRingFile}
sonatypeUsername={your sonatype username}
sonatypePassword={your sonatype password}
```
> Make publishing settings.

- build.gradle.kts
Since it is published before the three PR below were merged, release 1.0.1 to reflect the three PR.
- https://github.com/line/kotlin-jdsl/pull/6
- https://github.com/line/kotlin-jdsl/pull/4
- https://github.com/line/kotlin-jdsl/pull/2
> Release 1.0.1 to reflect the unreflected code.

- buildSrc/src/main/kotlin/PublishPlugin.kt
Motivation:
I found that the wrong email was written in the maven publishing settings.
Modifications:
Modify the developer's email address.
Result:
Users will be able to communicate with the correct email address.
> Correct typo in developer's email address.

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build.yaml
- CODEOWNERS
- README.md
- build.gradle.kts
- buildSrc/src/main/kotlin/JacocoExtensionPlugin.kt
- buildSrc/src/main/kotlin/Plugins.kt
- eclipselink/src/test/kotlin/com/linecorp/kotlinjdsl/eclipselink/integration/querydsl/select/EclipselinkCriteriaQueryDslSelectIntegrationTest.kt
- examples/eclipselink/build.gradle.kts
- examples/hibernate/build.gradle.kts
- examples/spring-boot-2.3/build.gradle.kts
- examples/spring-boot-2.4/build.gradle.kts
- examples/spring-boot-2.5/build.gradle.kts
- examples/spring-boot-2.6/build.gradle.kts
- settings.gradle.kts
- test-fixture/core/build.gradle.kts
- test-fixture/entity/build.gradle.kts
- test-fixture/integration/build.gradle.kts
Motivation:
We need to automatically measure code coverage and run tests whenever a PR is posted or the main branch is pushed to ensure that the project is working properly.
Refer to #20
-- korean
우리는 PR 이 올라오거나 main 브랜치가 push 될 때마다 자동으로 code coverage 를 측정하고 테스트를 수행하여 프로젝트가 정상적으로 동작하고 있다는 사실을 보장해야 합니다.
Modifications:
I modified jacoco, a code coverage plugin, to fit our project, which is a multi-module, automatically build and upload coverage using github actions.
Edited documents to include PR templates and contributors and badges.
-- korean
코드 커버리지 플러그인인 jacoco 를 멀티 모듈인 우리 프로젝트 특성에 맞게 수정하였고 github actions 를 이용하여 자동으로 빌드하고 커버리지를 업로드 하도록 하였습니다.
PR 템플릿과 contributor, badge 를 포함하는 문서를 수정했습니다.
Result:
There is no change experienced by users. Code coverage is uploaded whenever a PR is created …
> Code coverage management is required.

- .github/workflows/build.yaml
- README.md
* We are uploading code coverage whenever PR occurs due to github actions. This part is judged to be inappropriate, and the complete code coverage of our project was modified because it was thought that it should be uploaded only when a push to the main branch occurred.
Refer to #26 
-- korean
github actions 로 인해 PR 이 발생할 때마다 code coverage 를 업로드 하고 있습니다. 이부분은 적절하지 않다고 판단되며 완전한 우리 프로젝트의 코드 커버리지는 main 브랜치에 push 가 일어났을때만 업로드 되는게 맞다고 생각되어 수정을 하였습니다.
* The part of uploading code coverage in the workflow of github actions has been modified to be performed only when it is not a PR event.
-- korean
github actions 의 workflow 중 code coverage를 업로드하는 부분을 PR 이벤트가 아닐 경우에만 수행되도록 수정했습니다.
* Code coverage is not uploaded when a PR event occurs.
-- korean
PR 이벤트가 일어났을때는 code coverage 가 업로드 되지 않습니다.
> code coverage upload if github event is not pull request

- build.gradle.kts
- query/build.gradle.kts
publish query module & version up
If the query module is not published, there is a problem with the dependency and it is published.
kotlin-jdsl-query module published
> publish query module

- build.gradle.kts
- core/src/main/kotlin/com/linecorp/kotlinjdsl/querydsl/QueryDslImpl.kt
- reactive-core/src/main/kotlin/com/linecorp/kotlinjdsl/querydsl/ReactiveQueryDslImpl.kt
Please refer to #49 
-- korean
#49 이슈를 참고해주세요
* Each lazy clause of QueryDslImpl and ReactiveQueryDslImpl is modified to be a null, and it is modified to be loaded only when necessary so that it is created as an emptyList or emptyMap if it is not used in the methods that generate the spec.
-- korean
* QueryDslImpl, ReactiveQueryDslImpl 의 각 lazy 하게 사용될 수 있는 clause 들을 null  수정하고 필요할때만 로드되도록 spec 을 생성하는 메소드들에서 사용되지 않았을 경우 emptyList or emptyMap 으로 생성되게 수정하였습니다.
Users can use a little more memory resources efficiently when creating each query.
There is no change that users can directly feel.
-- korean
각 쿼리를 생성할때 조금 더 메모리 자원을 효율적으로 사용할 수 있습니다.
사용자가 직접 체감할 수 있는 변화는 없습니다.
> Improve create object performance for QueryDslImpl & ReactiveQueryDslImpl

- .github/workflows/build.yaml
Fix bug where Publish Unit Test Results does not work
I modified the test xml path. This can only be confirmed when it is actually merged.
There is no change perceived by users.
Merge immediately.
> fix publish unit test results path

- README.md
I was confused by the incorrect usage of some example code. improve it
Fixed incorrect usage of example code in the existing Select DTO section.
Added DTO Projection(select, selectMulti) section and example code to make it more understandable.
Add missing comma to Cross Join section example code
> Add DTO Projection section and example code

- README.md
- I found a typo in "Case When" section of the README.md.
- Correct typo in "Case When" section of README.md.
> Correct typo in "CASE WHEN" section of README.md

- README.md
There was no explanation about how to use left and right join on the `join` section, so the user is hard to find how to join them in different directions.
Add more explanation about using the `join` extension method.
#60
> docs: add explanation on left and right join

- .github/PULL_REQUEST_TEMPLATE.md
- examples/spring-boot-hibernate-reactive-2.6/src/main/kotlin/com/linecorp/kotlinjdsl/spring/data/example/QueryFactoryConfiguration.kt
- examples/spring-boot-hibernate-reactive-2.7/src/main/kotlin/com/linecorp/kotlinjdsl/spring/data/example/QueryFactoryConfiguration.kt
- query/src/main/kotlin/com/linecorp/kotlinjdsl/querydsl/expression/ExpressionDsl.kt
- query/src/test/kotlin/com/linecorp/kotlinjdsl/query/creator/JpaCriteriaQueryBuilderTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/select/AbstractCriteriaQueryDslSelectIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/criteriaquery/AbstractCriteriaDeleteIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/select/AbstractCriteriaQueryDslSelectIntegrationTest.kt
* Found some typos when running the tests.
* Wanted to improve the example.
* correct typo in some files
* Test files
* Released Method's Parameter name
* PR Template, typo is being applied in this conversation 🙂
* modifications to unify code style
* In the test code, `sut` is using private but it's not private in `JpaCriteriaQueryBuilderTest`
* Remove one trailing commas
* change example code to not use platform type
Platform type requires unnecessary boilerplate(`!!`, `let trick`, ...)
I think it should be best practice because many people can copy & paste that. Please review.
There is no change that users can feel.
> Correct typo and Unify code style

- README.md
- core/src/main/kotlin/com/linecorp/kotlinjdsl/querydsl/QueryDslImpl.kt
- core/src/test/kotlin/com/linecorp/kotlinjdsl/querydsl/where/QueryDslImplWhereTest.kt
- query/src/main/kotlin/com/linecorp/kotlinjdsl/querydsl/where/WhereDsl.kt
- reactive-core/src/main/kotlin/com/linecorp/kotlinjdsl/querydsl/ReactiveQueryDslImpl.kt
- reactive-core/src/test/kotlin/com/linecorp/kotlinjdsl/querydsl/where/ReactiveQueryDslImplWhereTest.kt
https://github.com/line/kotlin-jdsl/issues/74
- allow nullable predicates in where()
- support multi 'and conditions' with whereAnd(), whereOr()
- add test cases of changes
- add examples of changes
| docs        | Documentation only …
> allow null input and no need to use and() at WhereDsl

- README.md
- query/src/main/kotlin/com/linecorp/kotlinjdsl/query/spec/expression/ColumnSpec.kt
- query/src/main/kotlin/com/linecorp/kotlinjdsl/query/spec/expression/NestedColumnSpec.kt
- query/src/main/kotlin/com/linecorp/kotlinjdsl/querydsl/expression/ExpressionDsl.kt
- query/src/test/kotlin/com/linecorp/kotlinjdsl/query/spec/expression/NestedColumnSpecTest.kt
- test-fixture/entity/src/main/kotlin/com/linecorp/kotlinjdsl/test/entity/order/OrderGroup.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/criteriaquery/AbstractCriteriaDeleteIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/select/AbstractCriteriaQueryDslSelectIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/set/AbstractCriteriaQueryDslUpdateByIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/where/AbstractCriteriaQueryDslWhereIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/criteriaquery/AbstractCriteriaDeleteIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/select/AbstractCriteriaQueryDslSelectIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/set/AbstractCriteriaQueryDslUpdateByIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/where/AbstractCriteriaQueryDslWhereIntegrationTest.kt
* it's impossible query only the ref key without a join, if there was a associated relationship between entity classes
* Add NestedCol data class which implement `ExpressionSpec` and can fetch reference key.
* you can use this stmt for implicit join(example: https://github.com/kihwankim/kotlin-jdsl/commit/96f5b76003ab349c0759612ae2aa6a501af715e1)
| feat        | New Feature …
> support nested column fetch

- .github/PULL_REQUEST_TEMPLATE.md
- examples/spring-boot-hibernate-reactive-2.6/build.gradle.kts
- examples/spring-boot-hibernate-reactive-2.7/build.gradle.kts
- hibernate-reactive/build.gradle.kts
- libs.versions.toml
- spring/data-hibernate-reactive/build.gradle.kts
* The mutiny bundle name is incorrect, we need fix it. mutiny 1.7.0 has been upgraded. modified the PR template.
-- korean
* mutiny bundle 이름이 잘못되어 수정합니다. mutiny 1.7.0 이 업그레이드 되었습니다. PR 템플릿을 수정했습니다.
* Fixed the Mutiny typo in lib.versions.toml and upgraded the version.
* Added chore item to PR template.
-- korean
* lib.versions.toml 에서 Mutiny 오타를 수정하고 버전업을 진행했습니다.
* PR template 에 chore 항목을 추가했습니다. …
> chore: typo fix (mitiny -> mutiny), mutiny version 1.7.0

- README.md
- query/src/main/kotlin/com/linecorp/kotlinjdsl/query/spec/predicate/ExistsSpec.kt
- query/src/main/kotlin/com/linecorp/kotlinjdsl/querydsl/predicate/PredicateDsl.kt
- query/src/test/kotlin/com/linecorp/kotlinjdsl/query/spec/predicate/ExistsSpecTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/expression/AbstractCriteriaQueryDslExpressionIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/from/AbstractCriteriaQueryDslFromIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/from/AbstractCriteriaQueryDslFromTreatIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/groupby/AbstractCriteriaQueryDslGroupByIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/having/AbstractCriteriaQueryDslHavingIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/limit/AbstractCriteriaQueryDslLimitIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/orderby/AbstractCriteriaQueryDslOrderByIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/predicate/AbstractCriteriaQueryDslPredicateIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/select/AbstractCriteriaQueryDslSelectIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/set/AbstractCriteriaQueryDslUpdateByIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/querydsl/where/AbstractCriteriaQueryDslWhereIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/expression/AbstractCriteriaQueryDslExpressionIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/from/AbstractCriteriaQueryDslFromIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/from/AbstractCriteriaQueryDslFromTreatIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/groupby/AbstractCriteriaQueryDslGroupByIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/having/AbstractCriteriaQueryDslHavingIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/limit/AbstractCriteriaQueryDslLimitIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/orderby/AbstractCriteriaQueryDslOrderByIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/predicate/AbstractCriteriaQueryDslPredicateIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/select/AbstractCriteriaQueryDslSelectIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/set/AbstractCriteriaQueryDslUpdateByIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/querydsl/where/AbstractCriteriaQueryDslWhereIntegrationTest.kt
* There are not stmt for creating exists sql stmt in jdsl project
* Add ExistsSpec to enable `exists`/`not exist` sql stmt
| ci          | Change CI …
> Add ExistsSpec to enable exists not exist sql stmt

- query-jakarta/src/main/kotlin/com/linecorp/kotlinjdsl/query/spec/predicate/InValueSpec.kt
- query-jakarta/src/test/kotlin/com/linecorp/kotlinjdsl/query/spec/predicate/InValueSpecTest.kt
- query/src/main/kotlin/com/linecorp/kotlinjdsl/query/spec/predicate/InValueSpec.kt
- query/src/test/kotlin/com/linecorp/kotlinjdsl/query/spec/predicate/InValueSpecTest.kt
- test-fixture/integration-jakarta/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/criteriaquery/AbstractCriteriaDeleteIntegrationTest.kt
- test-fixture/integration-reactive-jakarta/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/criteriaquery/AbstractCriteriaDeleteIntegrationTest.kt
- test-fixture/integration-reactive/src/main/kotlin/com/linecorp/kotlinjdsl/test/reactive/criteriaquery/AbstractCriteriaDeleteIntegrationTest.kt
- test-fixture/integration/src/main/kotlin/com/linecorp/kotlinjdsl/test/integration/criteriaquery/AbstractCriteriaDeleteIntegrationTest.kt
This should prevent the unexpected behavior when providing empty lists to the in predicate function. Currently doing something like 
```kotlin
selectAll()
from<Contract>()
whereAnd(column(Contract::userId).`in`(emptyList()))
```
returns every record on the table. This has the potential to cause data leaks (and would currently cause this exact leak in our code if we had pushed it to production).
Changed InValueSpec to treat empty lists as a disjunction instead of a conjunction.
Closes issue #191 
Queries will no longer ignore predicates containing empty lists, treating them as always false. I did not see any mention of its current behavior in the documentation, so I expect this change will likely result in expected behavior for most users as the current behavior is fairly surprising.
The …
> Fixing in treating empty lists as a conjunction.

- build.gradle.kts
- examples/spring-boot-2.7/build.gradle.kts
- examples/spring-boot-3/build.gradle.kts
- examples/spring-boot-hibernate-reactive-2.7/build.gradle.kts
- examples/spring-boot-hibernate-reactive-3/build.gradle.kts
* With gradle upgrade to 8.1, you no longer need to declare `@Suppress("DSL_SCOPE_VIOLATION")` above plugins in build.gradle.kts.
-- korean
* gradle이 8.1로 업그레이드 되면서 더이상 `@Suppress("DSL_SCOPE_VIOLATION")` 을 build.gradle.kts 의 plugins 위에 선언할 필요가 없어졌습니다.
* Removed annotation from all build.gradle.kts files where `@Suppress("DSL_SCOPE_VIOLATION")` exists.
-- korean
* `@Suppress("DSL_SCOPE_VIOLATION")`가 존재하는 모든 build.gradle.kts 파일안에서 annotation 을 제거했습니다.
#Result:
There is no separate change felt by the user.
-- korean
유저가 느끼는 별도의 변화는 없습니다.
> remove unnecessarily @Suppress("DSL_SCOPE_VIOLATION") annotation in build.gradle.kts

- spring/data-core-jakarta/src/main/kotlin/com/linecorp/kotlinjdsl/spring/data/SpringDataQueryFactoryExtensions.kt
- spring/data-core-jakarta/src/test/kotlin/com/linecorp/kotlinjdsl/spring/data/SpringDataQueryFactoryExtensionsTest.kt
- spring/data-core/src/main/kotlin/com/linecorp/kotlinjdsl/spring/data/SpringDataQueryFactoryExtensions.kt
- spring/data-core/src/test/kotlin/com/linecorp/kotlinjdsl/spring/data/SpringDataQueryFactoryExtensionsTest.kt
* In JPA Criteria APIs, `singleResult` throws a `NoResultException` if the value doesn't exist. In this case, the unity of the whole code seems to be broken because the Try - Catch construct has to be used in all contexts. So I submit this pull request.
-- korean
* JPA Criteria API에서 `singleResult`는 값이 존재하지 않는 경우 `NoResultException`을 발생시킵니다. 이 경우 모든 컨텍스트에서 Try - Catch 구문을 사용해야 하기 때문에 전체 코드의 통일성이 깨지는 것 같습니다. 그래서 이 풀 리퀘스트를 제출합니다.
* Add `SpringDataQueryFactory.singleOrNullQuery` to `spring/data/SpringDataQueryFactoryExtensions.kt`
-- korean 
* `spring/data/SpringDataQueryFactoryExtensions.kt` 에 `SpringDataQueryFactory.singleOrNullQuery` 추가
* Can use `singleOrNullQuery` which will not throw `NoResultException`.
-- korean
* `NoResultException`이 발생하지 않는 `singleOrNullQuery`를 사용할 수 있습니다.
> feat: singleOrNullQuery to SpringDataQueryFactoryExtensions.kt

- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlMaxSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlMinSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlMaxSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlMinSerializerTest.kt
* Add `JpqlMinSerializer`
* Add test for `JpqlMinSerializer`, `JpqlMaxSerializer`
| …
> Add Min, Max jpql serializer

- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlAvgSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlCountSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSumSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlAvgSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSumSerializerTest.kt
- Implement `JpqlSumSerializer`, `JpqlAvgSerializer`
| refactor    | Not a bug fix or …
> Add Avg, Sum jpql serializers

- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/LiteralDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlLiteral.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/predicate/Predicates.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/predicate/impl/JpqlLike.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/predicate/impl/JpqlNotLike.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLikeSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLiteralSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotLikeSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLikeSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLiteralSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotLikeSerializerTest.kt
- add `escape` property to `JpqlLike` and `JpqlNotLike`
- Implement `JpqlNotLikeSerializer` and test …
> Add escape property for (NOT) LIKE  + add JpqlNotLikeSerializer

- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlCaseSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlCaseSerializerTest.kt
* Explain why you're making this change and what problem you're trying to solve.
Implement `JpqlCaseSerializer` …
> Add jpql case serializer

- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInSerializerTest.kt
* To solve the Issue #367 
* Implement `JpqlInSerializer`
* Implement Unit test for `JpqlInSerializer` …
> Add jpql In serializer 

- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotBetweenSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotBetweenSerializerTest.kt
* https://github.com/line/kotlin-jdsl/issues/377
* Add `JpqlNotBetweenSerializer`
| …
> Implements JpqlNotBetweenSerializer

- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotInSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotInSerializerTest.kt
* To solve the Issue #380 
* Implement `JpqlNotInSerializer`
* Implement Unit test for `JpqlNotInSerializer` …
> Add jpql NotIn serializer 

- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotInSubquerySerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotInSubquerySerializerTest.kt
* To solve the Issue #381 
* Implement `JpqlNotInSubquerySerializer`
* Implement Unit test for `JpqlNotInSubquerySerializer`
| ci          | Change CI …
> Add jpql NotIn subquery serializer

- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlDivideSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlDivideSerializerTest.kt
* To solve the Issue #337 
* Implement `JpqlDivideSerializer`
* Implement Unit test for `JpqlDivideSerializer` …
> Implement JpqlSerializer for JpqlDivide

- render/jpql/src/testFixtures/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/JpqlSerializerExtension.kt
-  Replace the use of the `arg` function with a more intuitive function in the `answer` block of Kotest.
- modify JpqlSerializerExtension.kt …
> test: change arg method in MockKAnswerScope

- .editorconfig
- example/eclipselink-javax/build.gradle.kts
- example/eclipselink/build.gradle.kts
- example/hibernate-javax/build.gradle.kts
- example/hibernate-reactive-javax/build.gradle.kts
- example/hibernate-reactive/build.gradle.kts
- example/hibernate/build.gradle.kts
- example/spring-batch-javax/build.gradle.kts
- example/spring-batch/build.gradle.kts
- example/spring-data-jpa-javax/build.gradle.kts
- example/spring-data-jpa/build.gradle.kts
- libs.example.versions.toml
- renovate.json
- settings.gradle.kts
-  `renovate` should be applied only on the develop branch and example projects.
- move original `libs.versions.toml` to `gradle/libs.version.toml` (default version catalog path)
- copy `libs.versions.toml` to `example.libs.versions.toml`
- update `.editorconfig` to change indent size of json file.
| fix         | Fix bug …
> chore: apply renovate only under example project

- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
move length, locate method above the function method in ExpressionsTest
| refactor    | Not a bug …
> Fix move length, locate method above the function method in ExpressionsTest

- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
There is no JpqlNotEqualSerializer in JpqlRenderContext, so a runtime error occurs when using NotEqual jpql
Add JpqlNotEqualSerializer to JpqlRenderContext …
> Add JpqlNotEqualSerializer to JpqlRenderContext

- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/LowerDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlLower.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLowerSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLowerSerializerTest.kt
- Support for String functions(lower)
- Add JpqlLower, JpqlLowerSerializer, dsl for lower function with tests …
> Add String functions(lower)

- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/UpperDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlUpper.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlUpperSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlUpperSerializerTest.kt
- Support for String functions(upper)
- Add JpqlUpper, JpqlUpperSerializer, dsl for upper function with tests …
> Add String functions(upper)

- docs/ko/jpql-with-kotlin-jdsl/README.md
I found a typo and awkward phrasing in docs.
- Correct typo in the word.
- Fix pharsing in the sentence. …
> docs: correct typo and fix phrasing in docs 

- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/path/impl/JpqlEntityProperty.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/path/impl/JpqlPathProperty.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/CombinedJpqlIntrospector.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/JpqlEntityIntrospector.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/JpqlIntrospector.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/JpqlPropertyDescription.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/JpqlPropertyIntrospector.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/JpqlRenderIntrospector.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/impl/JakartaJpqlIntrospector.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/impl/JavaxJpqlIntrospector.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/impl/JpqlProperty.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/impl/KotlinStyleJpqlPropertyIntrospector.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlEntityPropertySerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlPathPropertySerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/CombinedJpqlIntrospectorTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/impl/JakartaJpqlIntrospectorTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/impl/JavaxJpqlIntrospectorTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/introspector/impl/KotlinStyleJpqlPropertyIntrospectorTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlEntityPropertySerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlEntitySerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlEntityTreatSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlPathPropertySerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlPathTreatSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlValueSerializerTest.kt
- See #517 
This pull request has not been completed yet. 
It was created to receive a review to ensure that the work done so far has been implemented correctly.
- Change property type of `JpqlEntityProperty` and `JpqlPathProperty`.
- Add introspector for `KFunction1`
| docs        | …
> Add support for java getter

- docs/en/jpql-with-kotlin-jdsl/paths.md
- docs/en/jpql-with-kotlin-jdsl/spring-supports.md
- docs/ko/jpql-with-kotlin-jdsl/paths.md
- docs/ko/jpql-with-kotlin-jdsl/spring-supports.md
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/path/PathDslTest.kt
- dsl/jpql/src/testFixtures/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/entity/employee/Employee.kt
- dsl/jpql/src/testFixtures/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/entity/employee/FullTimeEmployee.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/path/Paths.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/path/PathsTest.kt
- query-model/jpql/src/testFixtures/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/entity/employee/Employee.kt
- src/main/kotlin/com/linecorp/kotlinjdsl/property/PropertyUtils.kt
- support/spring-batch-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/javax/autoconfigure/KotlinJdslAutoConfiguration.kt
- support/spring-batch/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/autoconfigure/KotlinJdslAutoConfiguration.kt
- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/autoconfigure/KotlinJdslAutoConfiguration.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/autoconfigure/KotlinJdslAutoConfiguration.kt
- follow up PR of #518 
- Add path method for `KFunction1`
- Add docs for java entity.
| refactor …
> Add path method for `KFunction1`

- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/writer/impl/DefaultJpqlWriter.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/writer/impl/DefaultJpqlWriterTest.kt
- String functions 추가 지원을 위한 작업 중, 예상과 다른 동작을 보이는 부분이 있어서 확인해보니,
3.0.0 부터 지원했던 비슷한 류의 upper(), lower() 등의 함수들도 이전과 다르게 아래와 같은 예기치 않은 동작을 보이는것을 확인했습니다.
- 기존에 `upper(:param1)` 처럼 렌더링 되던게 `upper:param1` 처럼 괄호가 누락된 채로 렌더링 되는 이슈.
- writer에 의해 writeParentheses() 내부에서 writeParam()만 호출하는 경우에 괄호가 누락 됨.
- 원인을 확인해보니 [d2cbb650](https://github.com/line/kotlin-jdsl/commit/d2cbb650a0c3e0e867282c0705698ff034bb756c#diff-2ec10a4f09b99aad188ce0a910134d75a4a517dd168548380e293920dd0d9531) 커밋의 `DefaultJpqlWriter.kt` 변경 이후 부터 영향을 받은듯합니다.
- develop 브랜치는 현재 3.10.0 준비중으로 보여, 3.0.2(hotfix)를 위해 main 브랜치에 PR 올립니다. 혹시나 문제가 없다면 develop에도 반영해 주시면 감사하겠습니다.
- writeParam() 메서드 호출시에도 write 메서드와 마찬가지로, nodes.add(String()) 추가.
- 이슈와 관련된 writeParentheses() 내부에서 writeParam()만 호출하는 경우에 대한 테스트 추가.
- Please commit your …
> Fix Malfunction - only call writeParam() methods inside writeParentheses() method

- docs/en/jpql-with-kotlin-jdsl/spring-supports.md
- docs/ko/jpql-with-kotlin-jdsl/spring-supports.md
- 한글 문서에서 오타로 의심되는 항목을 수정했습니다.
- 영어 원문은 `Kotlin JDSL provides KotlinJdslQueryProvider so that a JPQL query created in DSL can be executed on it.` 인데 마지막 it이 them 이 되어야 하는건지 확실하지 않네요 
| ci …
> docs: fix typo

- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/TrimFromStep.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/impl/TrimBothBuilder.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/impl/TrimBothDsl.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/impl/TrimBuilder.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/impl/TrimDsl.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/impl/TrimLeadingBuilder.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/impl/TrimLeadingDsl.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/impl/TrimTrailingBuilder.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/impl/TrimTrailingDsl.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/TrimBothDslTest.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/TrimDslTest.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/TrimLeadingDslTest.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/TrimTrailingDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlTrim.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlTrimBoth.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlTrimLeading.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlTrimTrailing.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlTrimBothSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlTrimLeadingSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlTrimSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlTrimTrailingSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlTrimBothSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlTrimLeadingSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlTrimSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlTrimTrailingSerializerTest.kt
- Support for String functions(trim)
- Add JpqlTrim, JpqlTrimSerializer, dsl for trim function with tests
- 현재 아래와 같이 trim을 구현하였는데, character 파라미터를 Expression으로 변환시
기존처럼 Expressions.value(it) 사용이 아닌 Expressions.charLiteral(it)을 사용하여 구현했습니다.
```kotlin
// Jpql.kt
@SinceJdsl("3.1.0")  
fun trim(  
value: Expressionable<String>,  
specification: JpqlTrim.Specification? = null,  
character: Char? = null,  
): Expression<String> {  
return Expressions.trim(  
value.toExpression(),  
specification,  
character?.let { Expressions.charLiteral(it) },  
)  
}
```
기존처럼 Expressions.value(it)를 사용할 경우, 
```kotlin
select(  
trim(path(Book::title), character = 'B'),  
).from(  
entity(Book::class),  
)
```
로 생성되는 JPQL은 `SELECT TRIM(:param1 FROM Book.title) FROM Book AS Book` 형태로 trim character 부분이 파라미터 …
> Add String functions(trim)

- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlFunctionSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlFunctionSerializerTest.kt
- The JPQL Function function is not operating properly. It should be created as function('function_name', ...), but it is created as function(function_name), making normal query execution impossible.
-- korean
- JPQL Function 기능이 정상적으로 동작하고 있지 않습니다. function('function_name', ...) 으로 생성 되어야 하지만 function(function_name) 으로 생성되고 있어 정상적인 쿼리 수행이 불가능합니다.
- Added a modification to wrap a single quotation in front of part.name of JpqlFunctionSerializer.
-- korean
- JpqlFunctionSerializer 의 part.name 앞에 single quotation 을 감싸는 수정을 추가하였습니다.
- You can now use JPQL functions normally.
-- korean
- JPQL의 function 을 정상적으로 사용할 수 있게 됩니다.
> fix the missing single quotation surrounding the function name of JpqlFunctionSerializer.

- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/SubstringDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlSubstring.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSubstringSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSubstringSerializerTest.kt
- Support for String functions(substring)
- Add JpqlSubstring, JpqlSubstringSerializer, dsl for substring function with tests …
> Add String functions(substring)

- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/ConcatDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlConcat.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlConcatSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlConcatSerializerTest.kt
- Support for String functions(concat)
- Add JpqlConcat, JpqlConcatSerializer, dsl for concat function with tests …
> Add String functions(concat)

- build.gradle.kts
- example/eclipselink-javax/build.gradle.kts
- example/eclipselink/build.gradle.kts
- example/hibernate-javax/build.gradle.kts
- example/hibernate-reactive-javax/build.gradle.kts
- example/hibernate-reactive/build.gradle.kts
- example/hibernate/build.gradle.kts
- example/spring-batch-javax/build.gradle.kts
- example/spring-batch/build.gradle.kts
- example/spring-data-jpa-javax/build.gradle.kts
- example/spring-data-jpa/build.gradle.kts
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlLiteral.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlNull.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/JpqlRenderClause.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/JpqlRenderStatement.kt
- render/src/main/kotlin/com/linecorp/kotlinjdsl/render/RenderContextImpl.kt
- Kotlin JDSL is compiled with the latest version of Kotlin, even if the latest version of the Kotlin API is not required.
- This makes Kotlin JDSL unusable for users on older versions of Kotlin.
- Compile with the lowest version of Kotlin that the Kotlin JDSL can support.
- Kotlin JDSL is now available for users on 1.7 and later versions who were unable to use it before.
- #560
> feat: support kotlin 1.7

- docs/en/jpql-with-kotlin-jdsl/expressions.md
- docs/ko/jpql-with-kotlin-jdsl/expressions.md
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/FloorDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlFloor.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlFloorSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlFloorSerializerTest.kt
- Support Arithmetic function FLOOR.
- Create Jpql model and serializer for ROUND And Create JpqlRound, Expressions, Serializer Test …
> Support Arithmetic function FLOOR

- docs/en/jpql-with-kotlin-jdsl/expressions.md
- docs/ko/jpql-with-kotlin-jdsl/expressions.md
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/SignDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlSign.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSignSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSignSerializerTest.kt
- Support an arithmetic function SIGN.
- Add jpql model and serializer for SIGN
| refactor    | …
> Support Arithmetic function SIGN

- docs/en/jpql-with-kotlin-jdsl/expressions.md
- docs/ko/jpql-with-kotlin-jdsl/expressions.md
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/LnDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlLn.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLnSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLnSerializerTest.kt
- Support an arithmetic function LN.
- Add jpql model and serializer for LN
| refactor    | Not a …
> Support Arithmetic function LN

- docs/en/jpql-with-kotlin-jdsl/expressions.md
- docs/ko/jpql-with-kotlin-jdsl/expressions.md
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/SizeDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlSize.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSizeSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSizeSerializerTest.kt
- Support an arithmetic function SIZE.
- Add jpql model and serializer for SIZE
| refactor    | …
> Support Arithmetic function SIZE

- docs/en/jpql-with-kotlin-jdsl/expressions.md
- docs/ko/jpql-with-kotlin-jdsl/expressions.md
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/IndexDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/predicate/impl/JpqlIndex.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlIndexSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlIndexSerializerTest.kt
- Support an arithmetic function INDEX.
- Add jpql model and serializer for INDEX
| refactor    | …
> Support Arithmetic function INDEX

- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/JpqlLocalDateTimeDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlLocalDateTime.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLocalDateTimeSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlJpqlLocalDateTimeSerializerTest.kt
- JDSL doesn't support `LOCAL DATETIME` in JPQL
- I create `localDateTime()` & `serializer` to support `LOCAL DATETIME` function  …
> Support Datetime function LOCAL DATETIME

- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/CurrentTimestampTest.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/LocalDateTimeDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlCurrentTimestamp.kt
- query-model/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/ExpressionsTest.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlCurrentTimestampSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlCurrentTimestampSerializerTest.kt
- JDSL doesn't support `CURRENT_TIMESTAMP` in JPQL
- Writing `currentTimestamp()` in Jpql, Expressions
- Creating a `JpqlCurrentTimestampSerializer`
- Add JpqlCurrentTimestampSerializer to `JpqlRenderContext`
- Write the respective test code
- Change FQCN for non-conventional code (`*.jpql.JpqlLocalDateTimeDslTest` -> `*.expression.LocalDateTimeDslTest`)
| fix         | Fix bug …
> Support Datetime function CURRENT_TIMESTAMP

- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlJpqlLocalDateTimeSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLiteralSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLocalDateSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLocalDateTimeSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLocalTimeSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNullSerializerTest.kt
- Unnecessary test code and inconsistent code style
- Remove unnecessary test stubbing code
- Write with a consistent code style …
> Remove unnecessary code, maintain a consistent code style

- docs/en/jpql-with-kotlin-jdsl/custom-dsl.md
- docs/ko/jpql-with-kotlin-jdsl/custom-dsl.md
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- support/spring-batch-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/javax/item/database/orm/KotlinJdslQueryProviderFactory.kt
- support/spring-batch-javax/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/javax/item/database/orm/KotlinJdslQueryProviderFactoryTest.kt
- support/spring-batch/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/item/database/orm/KotlinJdslQueryProviderFactory.kt
- support/spring-batch/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/item/database/orm/KotlinJdslQueryProviderFactoryTest.kt
- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/repository/KotlinJdslJpqlExecutor.kt
- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/repository/KotlinJdslJpqlExecutorImpl.kt
- support/spring-data-jpa-javax/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/repository/KotlinJdslJpqlExecutorImplTest.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/repository/KotlinJdslJpqlExecutor.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/repository/KotlinJdslJpqlExecutorImpl.kt
- support/spring-data-jpa/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/repository/KotlinJdslJpqlExecutorImplTest.kt
- related #563
- Add overloading methods that takes jdsl object
- Update documentation
> 영문문서는 한글 내용을 먼저 확인받고 진행해보겠습니다! …
> Support for creating queries via initialized JpqlDsl object

- example/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/example/spring/data/jpa/jpql/repository/book/BookRepository.kt
- support/spring-batch-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/javax/JpqlEntityManagerUtils.kt
- support/spring-batch-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/javax/item/database/orm/KotlinJdslQueryProvider.kt
- support/spring-batch-javax/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/javax/JpqlEntityManagerUtilsTest.kt
- support/spring-batch-javax/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/javax/item/database/orm/KotlinJdslQueryProviderTest.kt
- support/spring-batch/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/JpqlEntityManagerUtils.kt
- support/spring-batch/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/item/database/orm/KotlinJdslQueryProvider.kt
- support/spring-batch/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/JpqlEntityManagerUtilsTest.kt
- support/spring-batch/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/batch/item/database/orm/KotlinJdslQueryProviderTest.kt
- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/EnhancedTypedQuery.kt
- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/JpqlEntityManagerUtils.kt
- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/autoconfigure/KotlinJdslAutoConfiguration.kt
- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/extension/EntityManagerExtensions.kt
- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/repository/KotlinJdslJpqlExecutorImpl.kt
- support/spring-data-jpa-javax/src/main/kotlin/org/springframework/data/jpa/repository/support/CrudMethodMetadataPostProcessorAdaptor.kt
- support/spring-data-jpa-javax/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/JpqlEntityManagerUtilsTest.kt
- support/spring-data-jpa-javax/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/extension/EntityManagerExtensionsTest.kt
- support/spring-data-jpa-javax/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/repository/KotlinJdslJpqlExecutorImplTest.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/EnhancedTypedQuery.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/JpqlEntityManagerUtils.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/autoconfigure/KotlinJdslAutoConfiguration.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/extension/EntityManagerExtensions.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/repository/KotlinJdslJpqlExecutorImpl.kt
- support/spring-data-jpa/src/main/kotlin/org/springframework/data/jpa/repository/support/CrudMethodMetadataPostProcessorAdaptor.kt
- support/spring-data-jpa/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/JpqlEntityManagerUtilsTest.kt
- support/spring-data-jpa/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/extension/EntityManagerExtensionsTest.kt
- support/spring-data-jpa/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/repository/KotlinJdslJpqlExecutorImplTest.kt
- Kotlin JDSL does not support CrudMethodMetadata of Spring Data.
- Support `@Lock` of Spring Data.
- Support `@QueryHints` of Spring Data.
- #664
> feat: support crud method metadata of spring

- docs/ko/jpql-with-kotlin-jdsl/README.md
- docs/ko/jpql-with-kotlin-jdsl/expressions.md
There are typos in the Korean documentation
- fix typo in [README.md](https://github.com/line/kotlin-jdsl/blob/main/docs/ko/README.md) and [expressions.md](https://github.com/line/kotlin-jdsl/blob/main/docs/ko/jpql-with-kotlin-jdsl/expressions.md)
| docs        | Documentation only changed …
> docs: fix typo in korean documentation

- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotInSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlNotInSerializerTest.kt
- If in condition is used alone in the where clause and the compare values is empty, a malformed query is generated. 
- If compare values is empty, it renders 0 = 1 instead of nothing. 
| ci …
> fix: render false condition for in condition if the compare values is empty

- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/repository/KotlinJdslJpqlExecutorImpl.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/repository/KotlinJdslJpqlExecutorImpl.kt
- in spring data jpa SimpleJpaRepository class declare `@Transactional` but in select query they put readOnly true
- spring data KotlinJdslJpqlExecutor class's `@Transactional` readOnly option changed(false -> true) for select query
- in select query readOnly option changed true -> false
- closes #708
> [ISSUE-708] change @Transactional readOnly for select query

- .gitignore
- docs/ko/faq/how-do-i-use-kotlin-value-class.md
- docs/ko/jpql-with-kotlin-jdsl/value-class-informal-guidance..md
Please let me know which file I should add it to and I will move it.
I'm trying to write a Korean document and translate it into English.
- Add guide to how to use value class.
| ci          | …
> docs: add guide to using value classes

- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/autoconfigure/KotlinJdslJpaRepositoryFactoryBeanPostProcessor.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/autoconfigure/KotlinJdslJpaRepositoryFactoryBeanPostProcessor.kt
#723
- Check KotlinJdslJpqlExecutor super type
| refactor    | Not a bug fix or add feature, just …
> Support other custom repository implementations

- example/spring-data-jpa/src/test/kotlin/com/linecorp/kotlinjdsl/example/spring/data/jpa/jpql/select/SelectExample.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/JpqlRenderClause.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlDerivedEntitySerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlEntitySerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInnerAssociationFetchJoinSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInnerAssociationJoinSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInnerFetchJoinSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInnerJoinSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLeftAssociationFetchJoinSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLeftAssociationJoinSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLeftFetchJoinSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLeftJoinSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlDerivedEntitySerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlEntitySerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInnerAssociationFetchJoinSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInnerAssociationJoinSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInnerFetchJoinSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInnerJoinSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLeftAssociationFetchJoinSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLeftAssociationJoinSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLeftFetchJoinSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLeftJoinSerializerTest.kt
- Bug when creating a Predicate inside the on() method, using entity() added 'AS [alias]' resulting in syntax error
- Republishing due to changes in the from branch #729, #730
- Add Join, On clause to JpqlRenderClause 
- Modified conditional statements to include Join, On clause in EntitySerialiser (so that 'AS alias' is not added when serialising entities in On clause)
- Add code to update JpqlRenderClause to Join, On in FetchJoin, Join, Association join serialisers
- Modify test code according to serialiser modification …
> modify entity, join serializers to allow specify entity() as the on clause predicate

- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/repository/KotlinJdslJpqlExecutor.kt
- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/repository/KotlinJdslJpqlExecutorImpl.kt
- support/spring-data-jpa-javax/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/repository/KotlinJdslJpqlExecutorImplTest.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/repository/KotlinJdslJpqlExecutor.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/repository/KotlinJdslJpqlExecutorImpl.kt
- support/spring-data-jpa/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/repository/KotlinJdslJpqlExecutorImplTest.kt
- Spring Data supports a Limit class as a parameter in Repository since version 3.2.
- However, the Kotlin JDSL takes Spring Boot 2.7.9 and 3.0.3 as the minimum compatible version, which makes it difficult to support the Limit class.
- Add the parameters `offset: Int`, `limit: Int` to make Limit available in the Repository even for the minimum compatible Spring Boot version supported by the Kotlin JDSL.
- Users will be able to use offset and limit when using the findAll method of the KotlinJdslJpqlExecutor interface.
```kotlin
bookRepository.findAll(limit = 1) {
select(
path(Book::isbn),
).from(
entity(Book::class),
join(entity(BookPublisher::class)).on(path(BookPublisher::book).eq(entity(Book::class))),
).where(
path(BookPublisher::publisherId).eq(3),
)
}
bookRepository.findAll(offset = …
```
> feat: support limit in spring data repository

- docs/en/jpql-with-kotlin-jdsl/spring-supports.md
- docs/ko/jpql-with-kotlin-jdsl/spring-supports.md
- example/spring-data-jpa-javax/src/test/kotlin/com/linecorp/kotlinjdsl/example/spring/data/jpa/javax/jpql/select/SelectExample.kt
- example/spring-data-jpa/src/test/kotlin/com/linecorp/kotlinjdsl/example/spring/data/jpa/jpql/select/SelectExample.kt
- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/repository/KotlinJdslJpqlExecutor.kt
- support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/repository/KotlinJdslJpqlExecutorImpl.kt
- support/spring-data-jpa-javax/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/repository/KotlinJdslJpqlExecutorImplTest.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/repository/KotlinJdslJpqlExecutor.kt
- support/spring-data-jpa/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/repository/KotlinJdslJpqlExecutorImpl.kt
- support/spring-data-jpa/src/test/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/repository/KotlinJdslJpqlExecutorImplTest.kt
- Spring Data supports a stream as a return type.
- Add the `findStream()` functions to make the stream available in the repository.
- Users will be able to use the stream when using the `findStream()` method of the KotlinJdslJpqlExecutor interface.
- Close https://github.com/line/kotlin-jdsl/issues/802
```kotlin
employeeRepository.findStream {
selectNew<Row>(
path(EmployeeDepartment::departmentId),
count(Employee::employeeId),
).from(
entity(Employee::class),
join(Employee::departments),
).groupBy(
path(EmployeeDepartment::departmentId),
).orderBy(
path(EmployeeDepartment::departmentId).asc(),
)
}
```
> feat: support stream in spring data repository

- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/CustomExpressionDslTest.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/FunctionDslTest.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/NewDslTest.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/predicate/CustomPredicateDslTest.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/predicate/FunctionDslTest.kt
- The `vararg args: Any` type parameter was designed expecting only values, but the user expects a mix of values and expressions.
- So the user uses a mix of values and expressions, which results in an error that is difficult for the user to understand. 
- For functions that can mix values and expressions, add logic to prevent expressions from being treated as values. 
- The function can perform as the user expects it to.
> feat: handle mixed values and expressions in parameters

- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/select/SelectDslTest.kt
- Original `select(..)` functions used `reified` types for class parameters, making it hard to use them for generic classes even in the presence of class variables (`T::class`)
- Added class variable versions for every function in `select(..)` family.
- Tried to match style with existing class type functions
- Added some tests covering new functions
- One can write following code without an error:
```kotlin
abstract class JdslRepository<ENTITY : Any> { 
abstract fun findAll(): SelectQuery<ENTITY>
}
class TRepository<T: Any>(private val entityClass: KClass<T>) : JdslRepository<T> {
override fun findAll(): SelectQuery<T> {
return jpql {
select(entityClass, entity(entityClass)) // <- free of the error came from type erasure
.from(entity(entityClass))
}
}
}
```
- #825
> feat: Support select() with KClass<T> arguments

- docs/en/jpql-with-kotlin-jdsl/expressions.md
- docs/ko/jpql-with-kotlin-jdsl/expressions.md
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/CastStep.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/CastStepToString.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/StringCastStep.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/impl/JpqlCastStep.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/impl/JpqlCastStepToString.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/impl/JpqlStringCastStep.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/expression/ExpressionDslTest.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/Expressions.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlCast.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlLeft.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlReplace.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/JpqlRight.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlCastSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLeftSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlReplaceSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlRightSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlCastSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlLeftSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlReplaceSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlRightSerializerTest.kt
- This PR introduces new string manipulation functions (`CAST`, `LEFT`, `RIGHT`, `REPLACE`) to the Kotlin JDSL JPQL DSL. These functions align with the JPA 3.2 specification, providing enhanced capabilities for string operations directly within JPQL queries. This change aims to expand the functionality of Kotlin JDSL to support more advanced JPQL features as defined in the latest JPA specifications.
- Added `cast`, `left`, `right`, and `replace` functions to `dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt` for use within `jpql {}` blocks.  
- Implemented corresponding `JpqlCast`, `JpqlLeft`, `JpqlRight`, `JpqlReplace` expression types in `query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/expression/impl/`.  
- Added serializers for these new …
> feat: implement cast, right, left, replace expressions

- docs/en/jpql-with-kotlin-jdsl/statements.md
- docs/ko/jpql-with-kotlin-jdsl/statements.md
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/Jpql.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/select/impl/SetOperator.kt
- dsl/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/select/impl/SetOperatorSelectQueryBuilder.kt
- dsl/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/dsl/jpql/select/SetOperatorDslTest.kt
- example/hibernate-reactive/src/test/kotlin/com/linecorp/kotlinjdsl/example/hibernate/reactive/jakarta/jpql/select/IntersectMutinySessionExample.kt
- example/hibernate-reactive/src/test/kotlin/com/linecorp/kotlinjdsl/example/hibernate/reactive/jakarta/jpql/select/IntersectMutinyStatelessSessionExample.kt
- example/hibernate-reactive/src/test/kotlin/com/linecorp/kotlinjdsl/example/hibernate/reactive/jakarta/jpql/select/IntersectStageSessionExample.kt
- example/hibernate-reactive/src/test/kotlin/com/linecorp/kotlinjdsl/example/hibernate/reactive/jakarta/jpql/select/IntersectStageStatelessSessionExample.kt
- example/hibernate/src/test/kotlin/com/linecorp/kotlinjdsl/example/jpql/hibernate/select/IntersectExample.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/select/SelectQueries.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/select/impl/JpqlSelectQueryIntersect.kt
- query-model/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/querymodel/jpql/select/impl/JpqlSelectQueryIntersectAll.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/JpqlRenderContext.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSelectQueryIntersectAllSerializer.kt
- render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSelectQueryIntersectSerializer.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSelectQueryIntersectAllSerializerTest.kt
- render/jpql/src/test/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlSelectQueryIntersectSerializerTest.kt
This pull request introduces support for the `INTERSECT` and `INTERSECT ALL` set operators, aligning with the Jakarta Persistence 3.2 specification. These additions enhance Kotlin JDSL's capabilities for composing complex queries.
According to the JPQL BNF grammar in the Jakarta Persistence 3.2 specification, the `INTERSECT` operator has higher precedence than `UNION` or `EXCEPT`.
[BNF](https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#set-operators-in-select-statements) is below.
```
select_statement ::= union
union ::= intersection | union {UNION [ALL] | EXCEPT [ALL]} intersection
intersection ::= query_expression | intersection INTERSECT [ALL] query_expression
query_expression ::= select_query | (union)
```
Initially, we considered adding logic within the …
> feat: implement intersect, intersect-all for JPA 3.2 specification

- docs/en/SUMMARY.md
- docs/en/faq/how-to-use-database-specific-functions.md
- docs/ko/SUMMARY.md
- docs/ko/faq/how-to-use-database-specific-functions.md
The documentation lacked guidance on using database-specific functions that are not part of the standard JPQL specification. This PR adds a new FAQ page to explain how to use functions like `GROUP_CONCAT` with Kotlin JDSL and how to register them with the JPA provider.
- Added `docs/en/faq/how-to-use-database-specific-functions.md`
- Added `docs/ko/faq/how-to-use-database-specific-functions.md`
- Updated `docs/en/SUMMARY.md` and `docs/ko/SUMMARY.md` to include the new FAQ.
After this PR is merged, users will have a clear guide on how to use database-specific functions, enabling them to leverage the full power of their underlying database.
> docs: add FAQ on how to use database-specific functions
